###save
GRPC localhost:50051/blog.BlogService/save

{
  "author": "Pavel",
  "title": "Black Metal",
  "content": "Very Black content"
}

###findById
GRPC localhost:50051/blog.BlogService/findById

{
  "id": "64ada497cbd50668100beae8"
}

###updateById
GRPC localhost:50051/blog.BlogService/updateById

{
  "id": "64ada497cbd50668100beae8",
  "author": "Nikita",
  "title": "Pop",
  "content": "Pink pop content"
}

###deleteById
GRPC localhost:50051/blog.BlogService/deleteById

{
  "id": "64ad787d1326d32ea5af71ef"
}

###findAll
GRPC localhost:50051/blog.BlogService/findAll
